name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Lint
        run: go vet ./...

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v -coverprofile=coverage.cov -coverpkg ./... -covermode=atomic ./...

      - uses: codecov/codecov-action@v2.1.0
        with:
          files: coverage.cov
          flags: unittests
